version: '3.9'

volumes:
  postgres-data:
    external: false
  redis-data:
    external: false

networks:
  litminka-net:
    external: false

services:
  postgre-db:
    container_name: litminka-db
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: "litminka"
      POSTGRES_USER: "litminka"
      POSTGRES_PASSWORD: "password"
    ports:
      - target: 5432
        published: 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - litminka-net

  redis:
    container_name: redis
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    ports:
      - target: 6379
        published: 6379
    networks:
      - litminka-net

  nginx-proxy:
    container_name: nginx-proxy
    image: nginx:alpine
    ports:
      - target: 80
        published: 80
      - target: 443
        published: 443
    volumes:
      - ./cert:/etc/nginx/ssl:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - litminka-net

  litminka-api:
    image: ghcr.io/litminka/litminka-api:latest
    container_name: litminka-api
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - "ghcr.io/litminka/litminka-api:v2.0.0-alpha.1"
        - "ghcr.io/litminka/litminka-api:alpine"
    env_file: .env.docker
    networks:
      - litminka-net
