version: '3.9'
volumes:
  postgres-data:
    external: false # Внешние волюмы не привязываются к композу и при docker-compose down --volumes не удаляются
  redis-data:
    external: false

services:
  postgre-db:
    container_name: litminka-db
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: "litminka"
      POSTGRES_USER: "litminka"
      POSTGRES_PASSWORD: "password"
    ports:
      - target: 5432
        published: 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    ports:
      - target: 6379
        published: 6379

  nginx-proxy:
    container_name: nginx-proxy
    image: nginx:alpine
    ports:
      - target: 80
        published: 80
      - target: 443
        published: 443
    volumes:
      - ./cert:/etc/nginx/ssl:ro
      - ./nginx.conf/nginx.conf:/etc/nginx/nginx.conf:ro
