version: '3.9'
volumes:
  postgres-data:
    external: false # Внешние волюмы не привязываются к композу и при docker-compose down --volumes не удаляются
  redis-data:
    external: false

services:
  postgre-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: "litminka"
      POSTGRES_USER: "litminka"
      POSTGRES_PASSWORD: "password"
    ports:
      - target: 5432
        published: 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # - ./postgresql/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    ports:
      - target: 6379
        published: 6379

  nginx-proxy:
    image: nginx:1.23-alpine
    ports:
      - target: 80
        published: 80
      - target: 443
        published: 443
    volumes:
      - ./cert:/etc/certs:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # Глобальная конфигурация
      - ./nginx/conf.d:/etc/nginx/conf.d:ro # Специфичная конфигурация под домен (рекомендуется)
